/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICrossChainNameServiceLookup,
  ICrossChainNameServiceLookupInterface,
} from "../ICrossChainNameServiceLookup";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_name",
        type: "string",
      },
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "register",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICrossChainNameServiceLookup__factory {
  static readonly abi = _abi;
  static createInterface(): ICrossChainNameServiceLookupInterface {
    return new Interface(_abi) as ICrossChainNameServiceLookupInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICrossChainNameServiceLookup {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ICrossChainNameServiceLookup;
  }
}
