/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICrossChainNameServiceLookup,
  ICrossChainNameServiceLookupInterface,
} from "../../contracts/ICrossChainNameServiceLookup";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_name",
        type: "string",
      },
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "register",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICrossChainNameServiceLookup__factory {
  static readonly abi = _abi;
  static createInterface(): ICrossChainNameServiceLookupInterface {
    return new utils.Interface(_abi) as ICrossChainNameServiceLookupInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICrossChainNameServiceLookup {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ICrossChainNameServiceLookup;
  }
}
